### ISSUE TITLE
Copy raid ID into a new/existing tab

### ISSUE THREAD

**Issue by carks32** [NthMetal/gbraidfinder#10]
So, the other [raidfinder ](https://gbf.life/?locale=en)that I have been using for years has a neat feature that basically

1.  Gets the raid id onto your clipborad
2.  Opens a new gbf tab where you have to go and put the code yourself

And that has worked for a long time. Is it possible to add this kinf of feature to this raidfinder? Since the copy id option now just copies the id and takes a bit more to do the full rotation of getting into the raid.  Just wanted to ask that since it's probably the most trustworthy way to do it without getting banned since some people for some reason are getting banned the faster way that you do it.

**Comment by NthMetal** [comment]
Definitely possible to add this feature.

I plan on revamping the settings dialog sometime today anyway and adding a couple of other settings, so i'll add that in.

Thanks for your suggestion!

**Comment by NthMetal** [comment]
added with 8b93ad792b0aab8e1b0bf287bf2506a81c20ff3c
