### ISSUE TITLE
Siegfried HL is not included in the raid list

### ISSUE THREAD

**Issue by Vazkii** [NthMetal/gbraidfinder#11]

**Comment by NthMetal** [comment]
added with 2ebce9a138bccc46b4260b7bb0c156d9db1cacf2 and 4c37e872035efc760fa7f9ba37c2eed3de4f7541

Note: Raidfinder will go down for around 10minutes at Friday, November 18, 2022 1:00:00 PM [GMT-05:00] for this update.

**Comment by NthMetal** [comment]
successfully deployed
