### ISSUE TITLE
can't copy battle key

### ISSUE THREAD

**Issue by pohusun** [NthMetal/gbraidfinder#18]
when I choose copy battle key and Copy and Open GBF both,then I can't copy the latest battle key.It's remains an old one

**Comment by NthMetal** [comment]
I was unable to replicate this.

Can you provide more detail?

**Comment by pohusun** [comment]
> I was unable to replicate this.
> 
> Can you provide more detai

From what I just tried, 'copy battle key' works fine, but when I open 'copy battle key', there seems to be something wrong with the clipboard and I can't copy the battle key,it seems to be before I copy the battle key Just jump to the game page first

**Comment by pohusun** [comment]
> I was unable to replicate this.
> 
> Can you provide more detail?

From what I just tried, 'Copy Battle Key' works fine, but when I open 'Copy and Open GBF', there seems to be something wrong with the clipboard and I can't copy the battle key,It seems to jump to the game page first before I do the copy

**Comment by pohusun** [comment]
> > I was unable to replicate this.
> > Can you provide more detail?
> 
> From what I just tried, 'Copy Battle Key' works fine, but when I open 'Copy and Open GBF', there seems to be something wrong with the clipboard and I can't copy the battle key,It seems to jump to the game page first before I do the copy

using Microsoft Edge
Version 109.0.1518.61 (Official build) (64-bit)

**Comment by NthMetal** [comment]
should be fixed, let me know if there are any other issues
