### ISSUE TITLE
Clicking doesn't copy raid-code (Skyleap browser)

### ISSUE THREAD

**Issue by devzu** [NthMetal/gbraidfinder#20]
Hello!
Me and my friend play Granbklue in Skyleap and have used this wonderful raidfinder there too to have in a second or third tab. However a while ago(month? few weeks? not sure) the click-and-copy raid code feature didn't work anymore and I stopped using it. Today my friend and I talked about it and we realized we both have had this issue in skyleap, so I thought I should report it here.

Not really sure what I can provide with in terms of other than say it's Skyleap on android, version 1.22.1

**Comment by NthMetal** [comment]
Hey, thanks for the report. I can look into this, but it may be a little difficult because I'm not familiar with skyleap browser.

I have a couple questions about it:

Does copying work for other raid finders?

What copy settings are you using? Copy Battle Key and Copy and Open GBF or just Copy Battle Key?

**Comment by NthMetal** [comment]
Tested with skyleap on ios. I can copy raid codes on there now. Can you confirm?

**Comment by NthMetal** [comment]
Going to assume this is fixed. Let me know otherwise.

**Comment by devzu** [comment]
Hi! Sorry, I didn't have computer access until now. 
It's such a shame there's not much known about the skyleap browser, like if it's chromium and what version etc. It's really comfortable to use for GBF. I tried remote debugging to see if I found any error messages etc, but to no avail. 
1. Copy battle key works with other raidfinders, but not this one. Like https://gbf.kalvin.io/ . (https://github.com/kalvin807/gbf-raid-finder) 
2. Only tried with copy battle key until now, but just checked and the Copy and Open GBF doesn't work either. Tried all sorts of combos with the settings, nada. 😔 The clicked-on raid gets greyed out, so it registers a click at least. I wonder if it's the navigator
I'm on android and just checked, didn't work. Interesting that it doesn't behave the same on iOS Skyleap. Guess I'll have to go and use my old iPhone for GBF raids so i can enjoy this wondeful thing again before the twitter api gets nuked 🥲

**Comment by devzu** [comment]
Interestingly enough, I just checked the kalvin-gbf raidfinder, and in 2020 they did solve this issue that apparently is a thing specifically for skyleap on android. https://github.com/kalvin807/gbf-raid-finder/pull/1
From what i can understand, it's the skyleap on android that doesn't have a clipboard API,  so code with `navigator.clipboard.writeText(text);` won't work, I suppose? 
 I guess it really is skyleap behaving weirdly on specifcally android then. 😫

**Comment by NthMetal** [comment]
> Interestingly enough, I just checked the kalvin-gbf raidfinder, and in 2020 they did solve this issue that apparently is a thing specifically for skyleap on android. [kalvin807/gbf-raid-finder#1](https://github.com/kalvin807/gbf-raid-finder/pull/1) From what i can understand, it's the skyleap on android that doesn't have a clipboard API, so code with `navigator.clipboard.writeText(text);` won't work, I suppose? I guess it really is skyleap behaving weirdly on specifcally android then. 😫

oh cool, I didn't realize they found a fix for it. My copy text is here and it does try to use a fallback if it doesn't find navigator.clipboard (https://github.com/NthMetal/gbraidfinder/blob/master/front/src/app/home/home.component.ts#L540), but it seems like that's not good enough either. I can try running skyleap on an emulator, hopefully that will be good enough because I don't have access to an actual android device.

**Comment by NthMetal** [comment]
I think I fixed this. 

It seems like skyleap on android has navigator, but the writeText function fails. I also had a bug with copying from an invisible text area that I fixed and simplified that to get it to work. 

There also doesn't seem to be any regression with copy issues, but I didn't test everything so we'll see if anything else gets brought up.

@devzu Can you confirm that it works on your end?

**Comment by devzu** [comment]
It is working now! Wonderful! Thank you so much for looking into it and fixing so quickly!
