### ISSUE TITLE
Code does not copy when using click-though with macOS (Chrome)

### ISSUE THREAD

**Issue by charlesvngo** [NthMetal/gbraidfinder#21]
Hi there,

I normally play GBF in 2 windows with my right window as the game in focus and the left window as a raid finder. In macOS, to click an element on another window it needs to be in focus unless you force click-through by holding CMD + Click. When I do this to click on the raid finder while my game is in focus, the raid element will dim but the alert which says the raid has been copied does not fire and the raid code is not copied to clipboard. 

If I use your raid finder I need to click once to bring the raid finder into focus, click a raid to copy the code, click the game window to bring it in focus, click the enter ID field and then I can paste the code to join a raid. When I use other raid finders such as gbf.life, I can have my raid join text input in focus, cmd+click the raid I want to join in the other window, and paste the code immediately without changing focus.  

This is a macOS specific bug due to how click-through selects and element without bringing the window into focus.

**Comment by NthMetal** [comment]
This has possibly been fixed, I tested it on a mac and it looks alright. Can you confirm?

**Comment by charlesvngo** [comment]
Yep everything works as expected. Thanks for fixing it!
