### ISSUE TITLE
Improve settings form

### ISSUE THREAD

**Issue by NthMetal** [NthMetal/gbraidfinder#5]
![image](https://user-images.githubusercontent.com/7328874/200735909-dbdb2047-71cb-4d08-abb8-18328e2ed48f.png)

Settings form works, but can be improved.
Maybe double hp sliders, or sliders for players.
Maybe no scrolling if there's space.

**Comment by algusaem** [comment]
I've been trying to make the settings mat dialogue bigger so there's less scroll (if any) but I haven't found the way to access it from the scss to style it.

My intention was simply changing the width of the tab to a precentile (80% for example) so it grows or shrinks depending on the device, with the option of adding a viewport if it acts in a weird way.

I'll keep fiddling with it to see if I find the way to style it, hope this helps in any way!

**Comment by NthMetal** [comment]
improved with 8b93ad792b0aab8e1b0bf287bf2506a81c20ff3c
